version: 2.1

orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  helloworld:
    docker:
      - image: cimg/node:18.16.1
    steps:
      - checkout
      - run:
          name: Echo hello world
          command: echo "hello world!"

workflows:
  e2e_test_workflow_on_another_file:
    jobs:
      - helloworld
      - continuation/continue:
          name: front_e2e_test
          configuration_path: .circleci/e2e_test.yml
